# Generated by Django 3.0.1 on 2019-12-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='名前')),
                ('amount', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Food Expenses', '食費'), ('Water Bills', '水道代'), ('Gas Charges', 'ガス代'), ('Electricity Charges', '電気代'), ('Cellphone Charges', '携帯代'), ('Gacha Charges', 'ガチャ課金'), ('Communication Costs', '通信費'), ('Rent', '家賃')], max_length=100, verbose_name='カテゴリ')),
                ('balance_type', models.CharField(choices=[('Income', '収入'), ('Spending', '支出')], max_length=20, verbose_name='収支タイプ')),
            ],
        ),
    ]
