# Generated by Django 3.0.1 on 2019-12-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191229_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance_type',
            field=models.CharField(choices=[('収入', '収入'), ('支出', '支出')], max_length=20, verbose_name='収支タイプ'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='category',
            field=models.CharField(choices=[('給与所得', '給与所得'), ('食費', '食費'), ('Water Bills', '水道代'), ('ガス代', 'ガス代'), ('電気代', '電気代'), ('携帯代', '携帯代'), ('ガチャ課金', 'ガチャ課金'), ('通信費', '通信費'), ('交際費', '交際費'), ('交通費', '交通費'), ('家賃', '家賃')], max_length=100, verbose_name='カテゴリ'),
        ),
    ]
