# Generated by Django 3.0.1 on 2019-12-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191229_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='registered_date',
            field=models.DateField(null=True, verbose_name='日時'),
        ),
    ]
