# Generated by Django 3.0.1 on 2019-12-30 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191230_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BalanceDescription',
        ),
    ]
